Update for v12 compatibility
ghost-fvtt/fxmaster pull request #751
Opened 2024-07-31 21:29 UTC by Aioros

- on canvasReady, call drawDrawingsMask in an animation frame
- updated module manifest, removed older compatibility fields, removed manifestPlus field because I don't believe that's relevant anymore
- changed lingering references to globalThis.randomID() to foundry.utils.randomID()
- changed reference to PIXI.filter.DisplacementFilter to PIXI.DisplacementFilter

2024-07-31 22:32 UTC, Aioros commented
I just noticed you use Conventional Commits syntax. Let me know if you want me to redo the PR after review.

2024-08-01 06:22 UTC, ghost91- commented
Thanks! I’m currently on vacation and don’t have a laptop with me. I’ll take a look as soon as I’m back (11.08.2024).

2024-08-04 21:30 UTC, ThiefMaster commented
Tip, you can simply `git commit --amend` to change the commit message and then force-push it. No need to create a new PR just to change the commit message :)

2024-08-04 22:00 UTC, ThiefMaster commented
I think some more changes are needed: When dragging an effect from the "Special Effect Management" panel onto the scene, it creates a tile but it does not set the file path, so the tile remains empty (if I manually add the path to the tile afterwards, it's played correctly).

2024-08-04 22:16 UTC, ThiefMaster commented
Looks like it's because of this API change:

> Tile Document
> Removed automatic migration of the v9 `TileDocument#img` field which was deprecated in v10 and renamed to `TileDocument#texture#src`.

Adding this change fixes it:


```patch
diff --git a/src/fxmaster.js b/src/fxmaster.js
index 7e32150..77db41a 100644
--- a/src/fxmaster.js
+++ b/src/fxmaster.js
@@ -151,7 +151,7 @@ Hooks.on("dropCanvasData", async (canvas, data) => {
     flags: {},
     height: data.height,
     hidden: false,
-    img: data.file,
+    texture: {src: data.file},
     locked: false,
     occlusion: { mode: 1, alpha: 0 },
     overHead: false,
```

Not sure if this one is relevant as well (width/height are set, but no idea if negative values are ever used):

> Removed automatic migration of assigning a negative TileDocument#width or TileDocument#height in favor of assigning a negative TileDocument#texture#scaleX and TileDocument#texture#scaleY respectively.

2024-08-04 22:25 UTC, Aioros commented
I'll take a look at that too and see if I can add it, thanks. And thanks for the git tip too, God knows I still need them after all these years.

2024-08-06 17:16 UTC, Aioros commented
Updated the PR with @ThiefMaster's contribution and a new commit message.

2024-08-06 17:21 UTC, ThiefMaster commented on module.json
> +    "verified": "12.329"
```suggestion
    "verified": "12.330"
```

2024-08-24 15:09 UTC, Aioros commented
Apologies for being _that guy_: just checking if you had any time to take a look at this PR.

2024-08-26 11:59 UTC, ghost91- commented
No worries, I know the feeling ;)

I'm back from vacation now and I plan to do it this week.

2024-08-31 13:08 UTC, dralois requested changes
Overall it seems to work, one tiny change is required to make lint happy.

2024-08-31 13:08 UTC, dralois commented on src/fxmaster.js
The new line should be `texture: { src: data.file },`, otherwise lint will complain

2024-08-31 13:45 UTC, dralois approved these changes

2024-08-31 13:45 UTC, dralois commented on src/fxmaster.js
> +    texture: {src: data.file},
This change is required otherwise lint will complain
```suggestion
    texture: { src: data.file },
```

2024-08-31 13:47 UTC, dralois approved these changes

2024-08-31 13:47 UTC, dralois approved these changes

2024-09-08 09:11 UTC, ghost91- commented
Merged via #765. Thanks again for your work!

2024-09-08 09:11 UTC, closed without merging